// The fixture runner. Loads the corpus, derives the run id from the inputs, builds the
// context, and executes the pipeline.
//
// This module reads files. Stages do not. Keeping the I/O here is what lets every stage be
// tested with a plain object and what lets the whole run be reproduced from the corpus.

import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

import { canonical } from './canonical.mjs';
import { Ledger } from './ledger.mjs';
import { createContext, fixtureClock, recordedFetcher, recordedClock } from './context.mjs';
import { capturingFetcher, capturingModel, recordedModel } from './live/capture.mjs';
import { publicConfig } from './live/keys.mjs';
import { runPipeline } from './kernel.mjs';
import { defaultConfig, pipeline } from './config.mjs';

const here = dirname(fileURLToPath(import.meta.url));
export const FIXTURES_DIR = join(here, '..', 'fixtures');

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function loadFixtures(dir = FIXTURES_DIR) {
  // Sorted, because filesystem order is not a specification and a run that depends on it
  // is a run that replays differently on a different machine.
  const signalFiles = readdirSync(join(dir, 'signals'))
    .filter((name) => name.endsWith('.json'))
    .sort();

  // Two recording files, merged into one map before anything sees them, so ctx.fetch stays a
  // single lookup and a stage cannot tell which file a response came from.
  //
  // They are separate on disk because they are different KINDS of artifact.
  // recordings.json is hand-authored source data: what the enrichment sources say.
  // rubric.json is derived output, regenerated by scripts/record-rubric.mjs, because a rubric
  // recording is addressed by draft hash and therefore moves whenever a draft moves.
  const recordings = readJson(join(dir, 'recordings.json'));
  const rubric = readJson(join(dir, 'rubric.json'));

  return {
    signals: signalFiles.map((name) => readJson(join(dir, 'signals', name))),
    recordings: { ...recordings, ...rubric },
    approvals: readJson(join(dir, 'approvals.json')),
  };
}

// Derived, never random. Two runs over the same corpus and the same wiring share a run id,
// which is precisely what lets their ledgers be compared byte for byte.
//
// The signals are sorted before hashing, so the id identifies the input SET rather than the
// order the files happened to be listed in. The kernel sorts leads before processing them
// for the same reason, and an id that moved when the directory listing moved would undo
// that work.
// RECORDINGS ARE PART OF THE ID, added in M4 on the M2 review's recommendation. See
// docs/M4-SPEC.md §7 for the full argument; the short version is that the enrichment responses
// ARE inputs, and an id blind to half its inputs cannot answer the question it exists to answer.
// Without them, `replay` reports "the ledger differs", which is equally true of a code change, an
// evidence change and a wiring change. With them, a changed response changes the id and replay
// says the INPUTS changed; an unchanged id with a different ledger says the CODE changed.
//
// The WHOLE map, never the subset a run happened to read. A per-lead subset would make the id
// depend on which leads refused early, and that is an output. An id that moves when a decision
// moves cannot be used to ask whether the inputs moved.
//
// A live run passes {} here, because it has captured nothing at the moment its id is computed.
// What distinguishes one live run from the next is its clock start, which lives in config and is
// therefore already covered.
// NO RUN ID IS A FUNCTION OF A CREDENTIAL, added when the M4 ship-check found the signing secret in
// the shareable capture. The id is computed over the config as it may be WRITTEN DOWN, with secrets
// replaced by their fingerprints, which is exactly what the capture stores. The two have to agree:
// if the id covered the secret and the capture did not, a replay could never recompute the id it is
// checking against. Applied in fixture mode too, so there is one rule rather than two.
export function computeRunId({ pipeline: stages, config, signals, recordings = {} }) {
  const digest = createHash('sha256')
    .update(
      canonical({
        stages: stages.map((stage) => stage.name),
        config: publicConfig(config),
        signals: signals.map((signal) => canonical(signal)).sort(),
        recordings,
      }),
    )
    .digest('hex');
  return `run-${digest.slice(0, 12)}`;
}

export function buildRun({
  fixtures = loadFixtures(),
  config = defaultConfig,
  stages = pipeline,
  // Decisions recorded locally by `approve` / `reject`, layered OVER the shipped corpus. The
  // default is none, so executeFixtureRun and every determinism test see exactly the corpus a
  // fresh clone sees. The CLI is what passes real ones in.
  decisions = [],
} = {}) {
  // The human decisions are folded into the config the queue stage reads. They are part of the
  // run's inputs, so they are part of what the run id covers: approving something and running
  // again is a different run, and its id says so.
  const runConfig = {
    ...config,
    queue: { ...config.queue, approvals: [...fixtures.approvals, ...decisions] },
  };

  const run_id = computeRunId({
    pipeline: stages,
    config: runConfig,
    signals: fixtures.signals,
    recordings: fixtures.recordings,
  });
  const ledger = new Ledger();
  const ctx = createContext({
    ledger,
    clock: fixtureClock(runConfig.clock),
    fetch: recordedFetcher(fixtures.recordings),
    config: runConfig,
    run_id,
  });

  return { run_id, ledger, ctx, stages, signals: fixtures.signals };
}

// --- live and replay runs, new in M4 -------------------------------------------------------
//
// Both are the same eight stages the fixture run executes. What changes is where the responses, the
// completions and the instants come from, and all three arrive through the same seams.
//
// THE CAPTURE IS THE PRODUCT of a live run, as much as the ledger is. A ledger says what was
// decided; the capture says what the decisions were made from. Handing somebody one without the
// other gives them a verdict they cannot re-derive.

/**
 * A live run: real transports, a real clock, and a capture of everything both produced.
 *
 * The run id is computed from an EMPTY recordings seed, because at this moment the run has observed
 * nothing. What distinguishes one live run from the next is the clock start inside its config. The
 * seed is recorded in the inputs file so a replay recomputes the id exactly the way the run did,
 * rather than guessing which convention was in force.
 */
export function buildLiveRun({ signals, config, stages = pipeline, fetch, model, clock, decisions = [] }) {
  const runConfig = { ...config, queue: { ...config.queue, approvals: [...decisions] } };
  const recordingsSeed = {};
  const run_id = computeRunId({
    pipeline: stages,
    config: runConfig,
    signals,
    recordings: recordingsSeed,
  });

  const capture = {};
  const ledger = new Ledger();
  const ctx = createContext({
    ledger,
    clock,
    fetch: capturingFetcher(fetch, capture),
    model: model === undefined ? undefined : capturingModel(model, capture),
    config: runConfig,
    run_id,
  });

  return { run_id, ledger, ctx, stages, signals, capture, config: runConfig, recordingsSeed };
}

/**
 * A run rebuilt from a capture: recorded responses, recorded completions, recorded instants.
 *
 * Nothing here can reach the network and nothing needs a key, which is the point — whoever you hand
 * a run directory to can re-derive every decision in it without your credentials.
 */
export function buildReplayRun(inputs, stages = pipeline) {
  const run_id = computeRunId({
    pipeline: stages,
    config: inputs.config,
    signals: inputs.signals,
    recordings: inputs.recordings_seed ?? {},
  });
  const ledger = new Ledger();
  const ctx = createContext({
    ledger,
    clock: recordedClock(inputs.clock ?? []),
    fetch: recordedFetcher(inputs.recordings ?? {}),
    model: recordedModel(inputs.recordings ?? {}),
    config: inputs.config,
    run_id,
  });
  return { run_id, ledger, ctx, stages, signals: inputs.signals };
}

export async function executeFixtureRun(options = {}) {
  const { run_id, ledger, ctx, stages, signals } = buildRun(options);
  const report = await runPipeline({ stages, signals, ctx, ledger });
  return { run_id, ledger, report };
}
